<?php

namespace backend\controllers;

use common\models\User;
use yii\web\Controller;

class CoreController extends Controller
{
    public function beforeAction($action)
    {
        if(!in_array($action->id, [
            'login',
            'logout',
            'error'
        ])) {
            if(!\Yii::$app->user->isGuest){
                $user = User::findOne(\Yii::$app->user->id);
                if($user->status == 0)
                    $this->redirect(\yii\helpers\Url::toRoute('site/logout'));
            }elseif($action->id != 'logout'){
                $this->redirect(\yii\helpers\Url::toRoute('site/login'));
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
