<?php

namespace backend\components\Grid;

class DataColumn extends \kartik\grid\DataColumn{
    public $headerOptions = [];

    public $width = '60px';

    public $contentOptionsDefault = ['style' => 'word-wrap: break-word; work-break: break-all;'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!isset($this->headerOptions['width'])){
            $this->headerOptions['width'] = $this->width;
        }
        $this->contentOptions = array_merge($this->contentOptions, $this->contentOptionsDefault);
        $this->contentOptions['style'] =  isset($this->contentOptions['style']) ?  $this->contentOptions['style'] .' vertical-align: middle;' : "vertical-align: middle;";
    }
}