<?php
namespace backend\components\Grid;

use yii\base\Model;
use yii\helpers\Html;

class DateColumn extends DataColumn {
    public $headerOptions = ['width' => '120px'];

    public $filter = null;

    public $format = ['datetime', 'php:d/m/Y H:i:s'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->headerOptions = array_merge(['class' => 'text-center'], $this->headerOptions);
        $this->contentOptions = array_merge(['class' => 'text-center'], $this->contentOptions);
    }

//    protected function renderFilterCellContent()
//    {
//        if (is_string($this->filter)) {
//            return $this->filter;
//        }
//
//        $model = $this->grid->filterModel;
//        if ($this->filter !== false && $model instanceof Model && $this->attribute !== null && $model->isAttributeActive($this->attribute)) {
//            if ($this->grid->filterModel->hasErrors($this->attribute)) {
//                Html::addCssClass($this->filterOptions, 'has-error');
//                $error = ' ' . Html::error($this->grid->filterModel, $this->attribute, $this->grid->filterErrorOptions);
//            } else {
//                $error = '';
//            }
//            return Html::activeTextInput($this->grid->filterModel, $this->attribute, $this->filterInputOptions) . $error;
//        }
//        return parent::renderFilterCellContent();
//    }
}