<?php

namespace backend\components\Grid;

use backend\helpers\NumberHelper;

class NumberColumn extends DataColumn{
    public $headerOptions = ['width' => '40px', 'class' => 'text-right'];
    public $contentOptionsDefault = ['class' => 'text-right'];

    public $filter = null;

    protected  function renderDataCellContent($model, $key, $index)
    {
        $value = $this->getDataCellValue($model, $key, $index);
        return $value ? NumberHelper::formatNumber($value) : null; // TODO: Change the autogenerated stub
    }
}