<?php

namespace backend\components;

use yii\base\Widget;
use yii\helpers\Html;

class MenuMobileWidget extends Widget
{
    public $menus = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $html = "";
        foreach ($this->menus as $menu) {
            $html .= $this->renderHTML($menu);
        }
        return $html;
    }

    public function renderHTML($menuSelected)
    {
        $html = "";
        if (isset($menuSelected['allowAccess']) && !$menuSelected['allowAccess']) {
            return $html;
        }
        $hasChildren = isset($menuSelected['children']) && count($menuSelected['children']) > 0;
        $html = "<li>";
        $html .= "<a href='" . ($menuSelected['link'] ?? 'javascript:void(0);') . "'>";
        $html .= "<i class='fa fa-" . ($menuSelected['icon'] ?? '') . "'></i> " . ($menuSelected['label'] ?? "") . ($hasChildren ? " <span class='arrow'></span>" : '');
        $html .= "</a>";
        if($hasChildren) {
            $html .= "<ul class='sub-menu'>";
            foreach ($menuSelected['children'] as $child) {
                $html .= $this->renderHTML($child);
            }
            $html .= "</ul>";
        }
        $html .= "</li>";
        return $html;
    }
}