<?php

namespace backend\components;

use yii\base\Widget;
use yii\helpers\Html;

class MenuDesktopWidget extends Widget
{
    public $menus = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $html = "";
        $html .= '<ul class="nav navbar-nav row-fluid" >';
        foreach ($this->menus as $menu) {
            $html .= $this->renderHTML($menu);
        }
        $html .= '</ul>';
        return $html;
    }

    public function renderHTML($menuSelected, $level = 1)
    {
        $html = "";
        if (isset($menuSelected['allowAccess']) && !$menuSelected['allowAccess']) {
            return $html;
        }
        $hasChildren = isset($menuSelected['children']) && count($menuSelected['children']) > 0;
        $html = "<li " . ($hasChildren && $level == 1 ? 'class="classic-menu-dropdown"' : ($hasChildren && $level != 1 ? 'class="dropdown-submenu" aria-haspopup="true"' : '')) . ">";
        $html .= "<a href='" . ($menuSelected['link'] ?? 'javascript:void(0);') . "' " . ($hasChildren && $level == 1 ? "data-toggle='dropdown' data-hover='megamenu-dropdown' data-close-others='true'" : "") . ">";
        $html .= (isset($menuSelected['icon']) ? "<i  class='fa fa-" . ($menuSelected['icon'] ?? '') . "'></i> " : "") . ($menuSelected['label'] ?? "") . ($hasChildren && $level == 1 ? " <i class='fa fa-angle-down'></i>" : '');
        $html .= "</a>";
        if ($hasChildren) {
            $html .= "<ul class='dropdown-menu " . ($level == 1 ? 'pull-left' : "") . "'>";
            foreach ($menuSelected['children'] as $child) {
                $html .= $this->renderHTML($child, 2);
            }
            $html .= "</ul>";
        }
        $html .= "</li>";
        return $html;
    }
}