<?php

namespace backend\components;

use kartik\number\NumberControl as NumberControllerBase;

class MoneyControl extends NumberControllerBase{
    public function init()
    {
        $this->maskedInputOptions = [
            'prefix' => '',
            'suffix' => ' đ',
            'allowMinus' => false,
            'groupSeparator' => ',',
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}