<?php

namespace api\models;

use Yii;

/**
 * This is the model class for table "vh_cham_cong".
 *
 * @property int $id
 * @property string|null $date
 * @property int|null $nhan_vien_id
 * @property string|null $trang_thai
 * @property string|null $vao1
 * @property string|null $ra1
 * @property string|null $vao2
 * @property string|null $ra2
 * @property string|null $created
 * @property string|null $updated
 * @property string|null $ghi_chu
 *
 * @property User $nhanVien
 * @property ChamCongThang[] $chamCongThangs
 * @property ChiTietChamCongThang[] $chiTietChamCongThangs
 */
class ChamCong extends \yii\db\ActiveRecord
{
    const DIEN_THOAI = 'dien_thoai';
    const MAY_TINH = 'may_tinh';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vh_cham_cong';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date', 'vao1', 'ra1', 'vao2', 'ra2', 'created', 'updated'], 'safe'],
            [['nhan_vien_id'], 'integer'],
            [['trang_thai'], 'string'],
            [['ghi_chu'], 'string', 'max' => 500],
            [['nhan_vien_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nhan_vien_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'nhan_vien_id' => 'Nhan Vien ID',
            'trang_thai' => 'Trang Thai',
            'vao1' => 'Vao1',
            'ra1' => 'Ra1',
            'vao2' => 'Vao2',
            'ra2' => 'Ra2',
            'created' => 'Created',
            'updated' => 'Updated',
            'ghi_chu' => 'Ghi Chu',
        ];
    }

    /**
     * Gets query for [[NhanVien]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNhanVien()
    {
        return $this->hasOne(User::className(), ['id' => 'nhan_vien_id']);
    }

    /**
     * Gets query for [[ChamCongThangs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChamCongThangs()
    {
        return $this->hasMany(ChamCongThang::className(), ['cham_cong_id' => 'id']);
    }

    /**
     * Gets query for [[ChiTietChamCongThangs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChiTietChamCongThangs()
    {
        return $this->hasMany(ChiTietChamCongThang::className(), ['cham_cong_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
