<?php

namespace api\models;

use Yii;

/**
 * This is the model class for table "vh_nghi_phep".
 *
 * @property int $id
 * @property int|null $nhan_vien_phong_ban_id
 * @property string|null $nghi_tu_ngay
 * @property string|null $nghi_den_ngay
 * @property string|null $ly_do
 * @property int|null $nguoi_lam_don_id
 * @property int|null $truong_bo_phan_id
 * @property string|null $trang_thai
 * @property int|null $active
 * @property int|null $user_id
 * @property string|null $created
 * @property string|null $noi_dung
 * @property string|null $ghi_chu
 * @property string|null $ngay_de_nghi
 *
 * @property PhongBanNhanVien $nhanVienPhongBan
 * @property User $nguoiLamDon
 * @property User $user
 * @property TrangThaiNghiPhep[] $trangThaiNghiPheps
 */
class NghiPhep extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    const CHO_DUYET = "Chờ duyệt";
    public static function tableName()
    {
        return 'vh_nghi_phep';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nhan_vien_phong_ban_id', 'nguoi_lam_don_id', 'truong_bo_phan_id', 'active', 'user_id'], 'integer'],
            [['nghi_tu_ngay', 'nghi_den_ngay', 'created', 'ngay_de_nghi'], 'safe'],
            [['ly_do', 'trang_thai', 'noi_dung', 'ghi_chu'], 'string'],
            [['nhan_vien_phong_ban_id'], 'exist', 'skipOnError' => true, 'targetClass' => PhongBanNhanVien::className(), 'targetAttribute' => ['nhan_vien_phong_ban_id' => 'id']],
            [['nguoi_lam_don_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nguoi_lam_don_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nhan_vien_phong_ban_id' => 'Nhan Vien Phong Ban ID',
            'nghi_tu_ngay' => 'nghỉ từ ngày',
            'nghi_den_ngay' => 'nghỉ đến ngày',
            'ly_do' => 'lý do',
            'nguoi_lam_don_id' => 'Nguoi Lam Don ID',
            'truong_bo_phan_id' => 'Truong Bo Phan ID',
            'trang_thai' => 'Trang Thai',
            'active' => 'Active',
            'user_id' => 'User ID',
            'created' => 'Created',
            'noi_dung' => 'nội dung',
            'ghi_chu' => 'ghi chú',
            'ngay_de_nghi' => 'ngày đề nghị',
        ];
    }

    /**
     * Gets query for [[NhanVienPhongBan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNhanVienPhongBan()
    {
        return $this->hasOne(PhongBanNhanVien::className(), ['id' => 'nhan_vien_phong_ban_id']);
    }

    /**
     * Gets query for [[NguoiLamDon]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNguoiLamDon()
    {
        return $this->hasOne(User::className(), ['id' => 'nguoi_lam_don_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[TrangThaiNghiPheps]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTrangThaiNghiPheps()
    {
        return $this->hasMany(TrangThaiNghiPhep::className(), ['nghi_phep_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        $this->created = date('Y-m-d H:i:s');
        $this->trang_thai = self::CHO_DUYET;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            $YeuCau = new LichSuDuyetNghiPhep();
            $YeuCau->nghi_phep_id = $this->id;
            $YeuCau->trang_thai = self::CHO_DUYET;
            $YeuCau->user_duyet_id = $this->nhan_vien_phong_ban_id;
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
