<?php

namespace api\models;

use common\models\myAPI;
use Yii;

/**
 * This is the model class for table "{{%OTP_user}}".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $otp
 * @property string|null $exp_otp Thời hạn của OTP sử dụng 2p = time()+ 60*2
 * @property int|null $is_used
 * @property string|null $created
 * @property string|null $ip
 *
 * @property \common\models\User $user
 */
class OTPUser extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%OTP_user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'is_used'], 'integer'],
            [['created'], 'safe'],
            [['otp'], 'string', 'max' => 6],
            [['exp_otp', 'ip'], 'string', 'max' => 15],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'otp' => 'Otp',
            'exp_otp' => 'Exp Otp',
            'is_used' => 'Is Used',
            'created' => 'Created',
            'ip' => 'Ip',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        $this->otp = $this->generateNumericOTP(6);
        $this->exp_otp = time() + 60*2;
        $this->created = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function generateNumericOTP($n) {

        // Take a generator string which consist of
        // all numeric digits
        $generator = "1234567890";

        // Iterate for n-times and pick a single character
        // from generator and append it to $result

        // Login for generating a random character from generator
        //     ---generate a random number
        //     ---take modulus of same with length of generator (say i)
        //     ---append the character at place (i) from generator to result

        $result = "";

        for ($i = 1; $i <= $n; $i++) {
            $result .= substr($generator, (rand()%(strlen($generator))), 1);
        }

        // Return result
        return $result;
    }
    public function afterSave($insert, $changedAttributes)
    {
        myAPI::sendMailGun('Mã OTP của bạn là: <strong>'.$this->otp.'</strong>',
            ['hungdd@minhhien.com.vn' => 'HRM Pacific noreply'],
            $this->user->email,
            'HRM Pacific'
        );
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
