<?php

namespace api\models;

use common\models\User;
use Yii;
use yii\db\ActiveRecord;

/**
 * @property integer $id
 * @property integer $user_id
 * @property integer $vaitro_id
 *
 * @property User $user
 * @property VaiTro $vaitro0
 */
class Vaitrouser extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%vaitrouser}}';
    }

    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'vaitro_id'], 'integer'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['vaitro_id'], 'exist', 'skipOnError' => true, 'targetClass' => VaiTro::className(), 'targetAttribute' => ['vaitro_id' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Thành viên',
            'vaitro' => 'Vai trò',
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getVaitro0()
    {
        return $this->hasOne(VaiTro::className(), ['id' => 'vaitro_id']);
    }

    public function beforeDelete()
    {
        PhanQuyen::deleteAll(['vai_tro_id' => $this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
